version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
    file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
