name: Deploy to AWS EC2 via CodeDeploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip artifact
        run: zip -r mywebapp.zip . -x ".git/*"

      - name: Install AWS CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp mywebapp.zip s3://${{ vars.ARTIFACT_BUCKET }}/mywebapp.zip --region ${{ vars.AWS_REGION }}

      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name "${{ vars.APPLICATION_NAME }}" \
            --deployment-group-name "${{ vars.DEPLOYMENT_GROUP_NAME }}" \
            --s3-location bucket=${{ vars.ARTIFACT_BUCKET }},bundleType=zip,key=mywebapp.zip \
            --region ${{ vars.AWS_REGION }}

