name: Deploy to AWS EC2 via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip artifact
        run: zip -r mywebapp.zip . 

      - name: Upload to S3
        run: |
          aws s3 cp mywebapp.zip s3://${{ vars.ARTIFACT_BUCKET }}/mywebapp.zip \
            --region ${{ vars.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ vars.APPLICATION_NAME }} \
            --deployment-group-name ${{ vars.DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ vars.ARTIFACT_BUCKET }},bundleType=zip,key=mywebapp.zip \
            --region ${{ vars.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

