name: Deploy to AWS EC2 via CodeDeploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI v2
        run: |
          curl -sS "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build CodeDeploy bundle (.zip)
        run: |
          zip -r mywebapp.zip index.html appspec.yml scripts/

      - name: Upload artifact to S3
        env:
          BUCKET: kaq-project-bucket
        run: |
          KEY="mywebapp-${GITHUB_SHA}.zip"
          echo "KEY=$KEY" >> $GITHUB_ENV
          aws s3 cp mywebapp.zip "s3://$BUCKET/$KEY"

      - name: Create CodeDeploy deployment
        env:
          APP_NAME: MyWebApp
          GROUP_NAME: MyWebAppDG
          BUCKET: kaq-project-bucket
        run: |
          DEPLOY_ID=$(aws deploy create-deployment \
            --application-name "$APP_NAME" \
            --deployment-group-name "$GROUP_NAME" \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=$BUCKET,bundleType=zip,key=${KEY} \
            --query deploymentId --output text)
          echo "DEPLOY_ID=$DEPLOY_ID" >> $GITHUB_ENV
          echo "Started deployment $DEPLOY_ID"

      - name: Wait for deployment to finish (up to ~15m)
        run: |
          aws deploy wait deployment-successful --deployment-id "$DEPLOY_ID"
          aws deploy get-deployment --deployment-id "$DEPLOY_ID" --query 'deploymentInfo.status'
